### ISSUE TITLE
Rettelser til Before we Start 

### ISSUE THREAD

**Issue by chrbknudsen** [KUBDatalab/R-api#14]
Kan man lave først bullet punkt om til et link til 'Setup'
Kan man sætte et link ind til kursus kalenderen (er det i det hele taget en god ide?)
Kan man sætte et link til R-intro kurset (er det i det hele taget en god ide?)

**Comment by enerammer** [comment]
Jeg har lavet første punkt om til et link - synes det er en god ide, men er det for mærkeligt at det står med link font?
Synes det er en god ide med link til R-intro kurset, og har sat det ind, så må vi se om det er det rette sted.
Er lidt i tvivl ang. link til kalender, men det kan vi jo snakke om når vi ses
